{% set name = "venusian" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64ec8285b80b110d0ae5db4280e90e31848a59db98db1aba4d7d46f48ce91e3e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - venusian
    - venusian.tests
    - venusian.tests.fixtures
    - venusian.tests.fixtures.attrerror
    - venusian.tests.fixtures.attrerror_package
    - venusian.tests.fixtures.import_and_scan
    - venusian.tests.fixtures.importerror
    - venusian.tests.fixtures.importerror_package
    - venusian.tests.fixtures.importonly
    - venusian.tests.fixtures.nested
    - venusian.tests.fixtures.nested.sub1
    - venusian.tests.fixtures.nested.sub1.subsub1
    - venusian.tests.fixtures.nested.sub2
    - venusian.tests.fixtures.nested.sub2.subsub2
    - venusian.tests.fixtures.one
    - venusian.tests.fixtures.pyc
    - venusian.tests.fixtures.pyc.subpackage
    - venusian.tests.fixtures.subpackages
    - venusian.tests.fixtures.subpackages.childpackage
    - venusian.tests.fixtures.two

about:
  home: http://pylonsproject.org
  license: BSD-derived
  license_family: BSD
  license_file: LICENSE.txt
  summary: A library for deferring decorator actions
  doc_url: https://docs.pylonsproject.org/projects/venusian/
  dev_url: https://github.com/Pylons/venusian

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
