{% set name = "venusian" %}
{% set version = "3.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb72cdca6f3139a15dc80f9c95d3c10f8a54a0ba881eeef8e2ec5b42d3ee3a95

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
  run:
    - python >=3.5

test:
  imports:
    - venusian

about:
  home: http://pylonsproject.org
  license: BSD-derived
  license_family: BSD
  license_file: LICENSE.txt
  summary: A library for deferring decorator actions
  doc_url: https://docs.pylonsproject.org/projects/venusian/
  dev_url: https://github.com/Pylons/venusian

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - ChrisBarker-NOAA
