travis:
  secure:
    BINSTAR_TOKEN: nChjktxev9SwKaYiiKK+G6Z4G2dvRJLk0X7vpxEXPzNLoYQZwna76f+1Vx82WMO2H0fe1+iYje/JgGg+Ueahy6JgZX0+mQJeg9i69mkOr5xDKUJ9ocDQRbZ6ol4bbdfGAjcLf8Ia+W5BmFhG0SfTG5EtgJmp05l7TskmUwp4IRiAGL3H+fbFmv67IfLsmuS82T9+zor0/BZbRA+Q3IVpcMO1zvYQrDEKg+DvIfLH+EuYNvILBjia82NIBbmddIxVt/nANKSPT6Qt8cZdWgyb5yPUl/FTc/e6T7CDi//NXMavS0wkveMSTWU/3l5AIsSNx+YfZeJkbMpZ8/r8DR80Ntf7IllzvHpNoLSDHhLhqTiXrdF176sGwmq/fLJIQ3+UMMWWmGq/BEpcHly1bIfVeP+LNBHrKMExFNZSIJ1KCgpRvIWvbsKTqicqdYrAyPRpWNla5nPnCFsD871pVS6i1XSCtNbfnjVj4nSOYyJN0DX7qGosw+VQ9lQcwhjysXWzRdYwnpwk4Y05wKnHmEgDHvuiuBAzKJVTCdWlVmlUru2537Aoi5agqimJzhA0EP8edJ+aLS6K0KQ6Xbe85AAfAMJpOC3VQ8hQzyVDBqf6Q1mNyLwbdxy8CvTT4ejlyGqBNiFhyVlXH74zSfNy1pQApFkBA05vvXzsdHCOHBGMrH4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
